name: firebase1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^6.2.0
  flutter_onboarding_slider: ^1.0.11
  flutter_plugin_android_lifecycle: ^2.0.28
  flutter_social_button: ^1.1.4+1
  flutter_svg: ^2.2.0
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: any
  google_fonts: ^6.2.1
  google_sign_in: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  image_picker: ^1.1.2
  material_symbols_icons: ^4.0.0
  meta: ^1.16.0
  modal_progress_hud_nsn: ^0.5.1
  pin_code_fields: ^8.0.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/icons/
