// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzIn56RIUiTxH4jCp7FTx12qlcS5yPlA',
    appId: '1:1082262755861:web:015cbd8880326d22a6cc1c',
    messagingSenderId: '1082262755861',
    projectId: 'fir-1-8ae86',
    authDomain: 'fir-1-8ae86.firebaseapp.com',
    storageBucket: 'fir-1-8ae86.appspot.com',
    measurementId: 'G-WBG1JGS1GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDlqQKjkOo83Aszm7oY0IrYKdHno-EwM',
    appId: '1:1082262755861:android:b62a13827c988f89a6cc1c',
    messagingSenderId: '1082262755861',
    projectId: 'fir-1-8ae86',
    storageBucket: 'fir-1-8ae86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bbDeN0LetQoqHvqKmFgrUav1ox0EtdY',
    appId: '1:1082262755861:ios:074dabd064a296baa6cc1c',
    messagingSenderId: '1082262755861',
    projectId: 'fir-1-8ae86',
    storageBucket: 'fir-1-8ae86.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5bbDeN0LetQoqHvqKmFgrUav1ox0EtdY',
    appId: '1:1082262755861:ios:074dabd064a296baa6cc1c',
    messagingSenderId: '1082262755861',
    projectId: 'fir-1-8ae86',
    storageBucket: 'fir-1-8ae86.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQzIn56RIUiTxH4jCp7FTx12qlcS5yPlA',
    appId: '1:1082262755861:web:6ed07dc2e9459af2a6cc1c',
    messagingSenderId: '1082262755861',
    projectId: 'fir-1-8ae86',
    authDomain: 'fir-1-8ae86.firebaseapp.com',
    storageBucket: 'fir-1-8ae86.appspot.com',
    measurementId: 'G-RVX0KFB1QF',
  );
}
